# Student Alcohol Consumption

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np

### Step 2. Import the datasets student-mat and student-por and merge them.

In [3]:
pd.read_excel(r"C:\Users\hp\Downloads\studentmat.xlsx")

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [4]:
student_mat=pd.read_excel(r"C:\Users\hp\Downloads\studentmat.xlsx")
student_mat

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [5]:
student_por = pd.read_excel(r"C:\Users\hp\Downloads\studentpor.xlsx")
student_por

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [6]:
pd.merge(student_mat,student_por,how="outer")

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,15,R,GT3,T,1,1,at_home,other,...,3,1,2,1,1,1,4,13,13,13
1,GP,F,15,R,GT3,T,1,1,at_home,other,...,3,1,2,1,1,1,2,7,10,10
2,GP,F,15,R,GT3,T,1,1,other,other,...,5,5,5,1,1,1,2,8,9,9
3,GP,F,15,R,GT3,T,1,1,other,other,...,3,3,4,2,4,5,2,13,11,11
4,GP,F,15,R,GT3,T,1,1,other,other,...,3,3,4,2,4,5,2,8,6,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039,MS,M,19,U,GT3,T,3,2,at_home,services,...,3,2,1,1,1,3,4,6,11,9
1040,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9
1041,MS,M,20,R,GT3,T,1,1,other,other,...,4,4,3,2,4,4,12,8,11,10
1042,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
1043,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7

### Step 3. Assign it to a variable called df.

In [7]:
df=pd.merge(student_mat,student_por,how="outer")
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,15,R,GT3,T,1,1,at_home,other,...,3,1,2,1,1,1,4,13,13,13
1,GP,F,15,R,GT3,T,1,1,at_home,other,...,3,1,2,1,1,1,2,7,10,10
2,GP,F,15,R,GT3,T,1,1,other,other,...,5,5,5,1,1,1,2,8,9,9
3,GP,F,15,R,GT3,T,1,1,other,other,...,3,3,4,2,4,5,2,13,11,11
4,GP,F,15,R,GT3,T,1,1,other,other,...,3,3,4,2,4,5,2,8,6,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039,MS,M,19,U,GT3,T,3,2,at_home,services,...,3,2,1,1,1,3,4,6,11,9
1040,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9
1041,MS,M,20,R,GT3,T,1,1,other,other,...,4,4,3,2,4,4,12,8,11,10
1042,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
1043,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7

### Step 4.   For the purpose of this exercise slice the dataframe from 'school'until the 'guardian' column

In [11]:
df.loc[:,"school":"guardian"]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,15,R,GT3,T,1,1,at_home,other,home,mother
1,GP,F,15,R,GT3,T,1,1,at_home,other,home,mother
2,GP,F,15,R,GT3,T,1,1,other,other,course,mother
3,GP,F,15,R,GT3,T,1,1,other,other,reputation,mother
4,GP,F,15,R,GT3,T,1,1,other,other,reputation,mother
...,...,...,...,...,...,...,...,...,...,...,...,...
1039,MS,M,19,U,GT3,T,3,2,at_home,services,course,mother
1040,MS,M,19,U,LE3,T,1,1,other,at_home,course,father
1041,MS,M,20,R,GT3,T,1,1,other,other,course,other
1042,MS,M,20,U,LE3,A,2,2,services,services,course,other
1043,MS,M,21,R,GT3,T,1,1,other,other,course,other

### Step 5. Create a lambda function that captalize strings.

In [12]:
str_cols=df.select_dtypes(include="object").columns
str_cols

Index(['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob',
       'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic'],
      dtype='object')

In [13]:
df[str_cols]=df[str_cols].apply(lambda col: col.str.capitalize())
df[str_cols]

,school,sex,address,famsize,Pstatus,Mjob,Fjob,reason,guardian,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic
0,Gp,F,R,Gt3,T,At_home,Other,Home,Mother,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No
1,Gp,F,R,Gt3,T,At_home,Other,Home,Mother,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No
2,Gp,F,R,Gt3,T,Other,Other,Course,Mother,No,No,No,Yes,Yes,Yes,Yes,Yes
3,Gp,F,R,Gt3,T,Other,Other,Reputation,Mother,Yes,Yes,No,No,No,Yes,Yes,Yes
4,Gp,F,R,Gt3,T,Other,Other,Reputation,Mother,Yes,Yes,No,No,No,Yes,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039,Ms,M,U,Gt3,T,At_home,Services,Course,Mother,No,No,No,Yes,Yes,Yes,No,No
1040,Ms,M,U,Le3,T,Other,At_home,Course,Father,No,No,No,No,Yes,Yes,Yes,No
1041,Ms,M,R,Gt3,T,Other,Other,Course,Other,No,Yes,No,No,Yes,No,Yes,Yes
1042,Ms,M,U,Le3,A,Services,Services,Course,Other,No,Yes,Yes,No,Yes,Yes,No,No
1043,Ms,M,R,Gt3,T,Other,Other,Course,Other,No,No,No,No,No,Yes,No,No

### Step 6. Capitalize both Mjob and Fjob

In [14]:
df[["Mjob","Fjob"]].apply(lambda x:x.str.capitalize())

          Mjob      Fjob
0      At_home     Other
1      At_home     Other
2        Other     Other
3        Other     Other
4        Other     Other
...        ...       ...
1039   At_home  Services
1040     Other   At_home
1041     Other     Other
1042  Services  Services
1043     Other     Other

[1044 rows x 2 columns]

### Step 7. Print the last elements of the data set.

In [15]:
df.tail(1)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
1043,Ms,M,21,R,Gt3,T,1,1,Other,Other,...,5,5,3,3,3,3,3,10,8,7

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and captalize Mjob and Fjob.

#### yes, the orginal dataframe remains lowercase because the capitalization was applied only to the sliced data frame and not to be the original dataframe

### Step 9. Create a function called majority that return a boolean value to a new column called legal_drinker

In [16]:
def majority(age):
    return age>=18 
majority(df["age"])

0       False
1       False
2       False
3       False
4       False
        ...
1039     True
1040     True
1041     True
1042     True
1043     True
Name: age, Length: 1044, dtype: bool

In [17]:
df["legal_drinker"]=df["age"].apply(majority)
df["legal_drinker"]

0       False
1       False
2       False
3       False
4       False
        ...
1039     True
1040     True
1041     True
1042     True
1043     True
Name: legal_drinker, Length: 1044, dtype: bool

In [18]:
df[["age","legal_drinker"]]

      age  legal_drinker
0      15          False
1      15          False
2      15          False
3      15          False
4      15          False
...   ...            ...
1039   19           True
1040   19           True
1041   20           True
1042   20           True
1043   21           True

[1044 rows x 2 columns]

### Step 10. Multiply every number of the dataset by 10.

In [19]:
df[df.select_dtypes(include="number").columns]*=10
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,legal_drinker
0,Gp,F,150,R,Gt3,T,10,10,At_home,Other,...,10,20,10,10,10,40,130,130,130,False
1,Gp,F,150,R,Gt3,T,10,10,At_home,Other,...,10,20,10,10,10,20,70,100,100,False
2,Gp,F,150,R,Gt3,T,10,10,Other,Other,...,50,50,10,10,10,20,80,90,90,False
3,Gp,F,150,R,Gt3,T,10,10,Other,Other,...,30,40,20,40,50,20,130,110,110,False
4,Gp,F,150,R,Gt3,T,10,10,Other,Other,...,30,40,20,40,50,20,80,60,50,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039,Ms,M,190,U,Gt3,T,30,20,At_home,Services,...,20,10,10,10,30,40,60,110,90,True
1040,Ms,M,190,U,Le3,T,10,10,Other,At_home,...,20,30,30,30,50,50,80,90,90,True
1041,Ms,M,200,R,Gt3,T,10,10,Other,Other,...,40,30,20,40,40,120,80,110,100,True
1042,Ms,M,200,U,Le3,A,20,20,Services,Services,...,50,40,40,50,40,110,90,90,90,True
1043,Ms,M,210,R,Gt3,T,10,10,Other,Other,...,50,30,30,30,30,30,100,80,70,True